language: java
sudo: false
jdk:
- oraclejdk7
- openjdk7
script: "./build.sh"
after_success:
- "./gradlew jacocoTestReport coveralls -S"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- openssl aes-256-cbc -K $encrypted_aca3b1502f6f_key -iv $encrypted_aca3b1502f6f_iv -in gradle.properties.enc -out gradle.properties -d
notifications:
  email: false